import os

HDD_DATASET_ROOT = "./dataset"
SSD_DATASET_ROOT = "./dataset"
RUNS = "./runs"
DEPTH_WIDTH = 320
DEPTH_HEIGHT = 240
MC_STEPS = 20
MC_DROPOUT_RATE = 0.25
WORLD_DISTANCE_THRESHOLD = 1.0
COVERAGE_IGNORE_THRESHOLD = 0.35
VISUALIZATION = False
